import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#ffffff',
      black: '#000000',
      // Dorisio Design System Colors (Dark Theme - Black bg with Yellow accent)
      background: '#0a0a0a',
      foreground: '#ffffff',
      primary: '#ffbf1f',
      'primary-foreground': '#0a0a0a',
      secondary: '#1a1a1a',
      'secondary-foreground': '#ffffff',
      muted: '#404040',
      'muted-foreground': '#888888',
      ink: '#ffffff',
      'ink-foreground': '#0a0a0a',
      soft: '#1a1a1a',
      gold: '#ffbf1f',
      'gold-foreground': '#0a0a0a',
      line: '#2a2a2a',
      border: '#2a2a2a',
      canvas: '#0a0a0a',
      'surface-soft': '#121212',
      'surface-card': '#1a1a1a',
      'surface-elevated': '#242424',
      body: '#cccccc',
      'body-strong': '#e6e6e6',
      hairline: '#2a2a2a',
      'hairline-strong': '#3a3a3a',
      'surface-yellow-band': '#ffbf1f',
      'on-primary': '#0a0a0a',
      'on-dark': '#ffffff',
      'on-yellow': '#0a0a0a',
      'accent-emerald': '#22c55e',
      'accent-rose': '#ef4444',
      'accent-blue': '#3b82f6',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
    },
    extend: {
      fontSize: {
        'display-xl': '72px',
        'display-lg': '56px',
        'display-md': '40px',
        'display-sm': '32px',
        'title-lg': '24px',
        'title-md': '18px',
        'title-sm': '16px',
        'stat-display': '56px',
        'body-md': '16px',
        'body-sm': '14px',
        caption: '13px',
        'caption-uppercase': '12px',
      },
      fontWeight: {
        display: '700',
        title: '600',
        body: '400',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        pill: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      letterSpacing: {
        tight: '-2.5px',
        tighter: '-2px',
        'tighter-1.5': '-1.5px',
        'tighter-1': '-1px',
        'tighter-0.3': '-0.3px',
      },
      lineHeight: {
        tight: '1.05',
        tighter: '1.1',
        snug: '1.15',
        normal: '1.2',
        relaxed: '1.3',
        loose: '1.4',
        looser: '1.55',
      },
    },
  },
  plugins: [],
};

export default config;
